/*Este fichero sólo es para guardar la creación de la BBDD.
Las queries están guardadas en constantes y ficheros,
y se guardan también aquí por si se perdieran.*/

CREATE DATABASE IF NOT EXISTS proyecto_java;

USE proyecto_java;

CREATE TABLE IF NOT EXISTS USUARIOS(ID INT AUTO_INCREMENT PRIMARY KEY,NOMBRE VARCHAR(24) UNIQUE,PASSWORD VARCHAR(255),NICKNAME VARCHAR (24));

CREATE TABLE IF NOT EXISTS PUNTUACIONES(ID INT,PUNTUACION INT,NIVEL INT,CONSTRAINT PUNTOS_PK PRIMARY KEY (ID, PUNTUACION, NIVEL),CONSTRAINT PUNTOS_FK FOREIGN KEY (ID) REFERENCES USUARIOS (ID) ON DELETE CASCADE);

INSERT IGNORE INTO USUARIOS VALUES (null, 'prueba','123','_prueba_');
INSERT IGNORE INTO USUARIOS VALUES (null, 'Ivan','123','Profe_PROG');
INSERT IGNORE INTO USUARIOS VALUES (null, 'Javier','123','Profe_SI');
INSERT IGNORE INTO USUARIOS VALUES (null, 'Jesus','123','Profe_BBDD');
INSERT IGNORE INTO USUARIOS VALUES (null, 'Guillermo','123','Profe_MARCAS');
INSERT IGNORE INTO USUARIOS VALUES (null, 'Juan','123','Profe_FOL');

INSERT IGNORE INTO PUNTUACIONES VALUES (1,10,1);
INSERT IGNORE INTO PUNTUACIONES VALUES (2,417,3);
INSERT IGNORE INTO PUNTUACIONES VALUES (3,222,2);
INSERT IGNORE INTO PUNTUACIONES VALUES (4,222,2);
INSERT IGNORE INTO PUNTUACIONES VALUES (5,540,3);
INSERT IGNORE INTO PUNTUACIONES VALUES (6,76,1);
INSERT IGNORE INTO PUNTUACIONES VALUES (1,10,3);
INSERT IGNORE INTO PUNTUACIONES VALUES (2,205,2);
INSERT IGNORE INTO PUNTUACIONES VALUES (3,77,1);
INSERT IGNORE INTO PUNTUACIONES VALUES (4,100,1);
INSERT IGNORE INTO PUNTUACIONES VALUES (5,210,2);
INSERT IGNORE INTO PUNTUACIONES VALUES (6,417,3);